### ISSUE TITLE
I lost the font-family when I export

### ISSUE THREAD

**Issue by reyimaginario** [eKoopmans/html2pdf#17] opened 2017-06-22 20:26 UTC
Hello @eKoopmans 

I'm having problems with the fonts when I export the html to pdf. The pdf has some font different than the one I'm using in the web page.
Could you please assist me?
I'm new in this world of JavaScript so it is possible I'm doing something wrong.

Here's my code:
(I'm really sorry but I don't know how to paste my code without turn it as a web so I'm gonna try to explain it)

--------------------------------------------------------------------

* I included the files in the order you mentioned:
<link rel="stylesheet" type="text/css" href="css/estilos.css">
<script src="jspdf.min.js"></script>
<script src="html2canvas.min.js"></script>
<script src="html2pdf.js"></script>
<script type="text/javascript" src="js/myjs.js"></script>

* I have a header h1:
A B C D E F G H I J K L M N O P Q R S T U V W X Y Z

* A paragraph into a div id="div1"  tag
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

* And a button "Export" to execute the JS
button id="attr" onclick="print_pdf()"   Export   /button

--------------------------------------------------------------------

css:

h1 { 	font-family: "Helvetica Neue",Helvetica,Arial,sans-serif; }

#div1 {
	border: 1px solid black;
	background-color: lightblue;
	font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
	font-size: 20x;
	color: #FF0000;
	padding-top: 30px;
	padding-bottom: 30px;
	padding-left: 15px;
	padding-right: 15px;
}

--------------------------------------------------------------------

my JS:

function print_pdf() {
	var element = document.body;
	var parameters = { 
						margin:       1,
						filename:     'myfile_png.pdf',
						image:        { type: 'png' },
						html2canvas:  { dpi: 192, letterRendering: true },
						jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
					 };
	html2pdf(element, parameters);
}

--------------------------------------------------------------------

Thank you in advance for your time.

**Comment by eKoopmans** [comment] 2017-07-03 04:54
Hi @reyimaginario, sorry it took a while for me to get back to you. I've created a Fiddle of your problem [here](https://jsfiddle.net/m1u623oa/1/).

The problem is in html2canvas (which html2pdf uses) - in the Fiddle I removed the call to html2pdf and replaced it with just html2canvas to confirm that it is the problem. I also changed the header font to only use Arial, and you'll see that it renders correctly, which means the problem is with declaring multiple fonts in the CSS.

I found two issues on html2canvas that look related: [here](https://github.com/niklasvh/html2canvas/issues/479) and [here](https://github.com/niklasvh/html2canvas/issues/796). There's not much I can do to fix those issues right now, sorry, but I'm working on a new HTML renderer of my own with the goal of removing the dependency on html2canvas. Might be a while before that's working though!

**Comment by reyimaginario** [comment] 2017-07-03 15:48
Thank you so much for your assistance!

**Comment by eKoopmans** [comment] 2017-11-27 09:45
Closing - this is an issue in html2canvas, can't be solved on this end.

**Closed by eKoopmans** 2017-11-27 09:45 UTC

**Comment by OkeleyeVick** [comment] 2023-08-06 12:21
> 

Hi, were you able to come up the HTML rendere?
