### ISSUE TITLE
merge pdf from different DIVs

### ISSUE THREAD

**Issue by sandroden** [eKoopmans/html2pdf#187] opened 2018-12-17 07:51 UTC
I need to return a pdf that merges 2+ pages from different divs. Each page is rendered in different containers (vuejs) and I need to create a single pdf file. I believe I can store the pdf in a variable and I was looking at the possibility to merge them together when I saw in issue #43 this code:

```
html2pdf().from(targetElement).toPdf().get('pdf').then(function (pdf) {
  pdf.addPage();
}).toPdf().save();
```
that makes me belive there should be a way with the html2pdf api, but I can't understand it completely: what does `.get('pdf')` return? `pdf.addPage()` has a very sexy name for me in this moment, how do I add content there?

**Comment by eKoopmans** [comment] 2019-01-16 05:01
Hi @sandroden @charutiwari04, yes the API allows quite a bit of flexibility. The example you linked prints the *same* content twice, but it could be easily modified for your purposes:

```js
// Puts the first element into the PDF, goes to a new page, and puts a second element on.
html2pdf().from(element1).toPdf().get('pdf').then(function (pdf) {
    pdf.addPage();
}).from(element2).toPdf().save();
```

To answer your question, `.get('pdf')` gives you access to the underlying [jsPDF object](https://github.com/MrRio/jsPDF), which you can do absolutely anything you want with. `.get()` exposes whatever property you want in the following `.then()` statement, so you see in the `.then()` we get access to the PDF object and can manipulate it, and then continue on our merry way. html2pdf lets you chain multiple commands together to accomplish lots of different outcomes.

Hope that helps! I'm closing the issue, just reopen it if this didn't solve your problem. Good luck!

**Closed by eKoopmans** 2019-01-16 05:01 UTC

**Comment by sandroden** [comment] 2019-01-25 11:22
Thank you very much @eKoopmans, it works like a charm! I needed to set it up in a dynamic way (variable number of pages) so I post here what it's working for me:

```js
      let doc = html2pdf().set(opt).from(pages[0]).toPdf()
      for (let j = 1; j < this.pages.length; j++) {
        doc = doc.get('pdf').then(
          pdf => { pdf.addPage() }
        ).from(pages[j]).toContainer().toCanvas().toPdf()
      }
      doc.save()  
```

**Comment by chenyiqiao** [comment] 2020-07-09 01:48
Hi,@sandroden thanks, your post helps a lot. But i still have a problem.

My html page could be very long, so I have to consider about the canvas size limit. I used your code to split html page to several parts, convert them into pdf with and stiches them together afterwards. But I found that the gap between two parts is not perfectly displayed. Say, The last page of first pdf has only one line, then rest of the page is totally empty.It looks like the gap is not properly merged. Did you run into the same problem?

**Comment by BalajiArun004** [comment] 2022-08-16 11:19
> Thank you very much @eKoopmans, it works like a charm! I needed to set it up in a dynamic way (variable number of pages) so I post here what it's working for me:
> 
> ```js
>       let doc = html2pdf().set(opt).from(pages[0]).toPdf()
>       for (let j = 1; j < this.pages.length; j++) {
>         doc = doc.get('pdf').then(
>           pdf => { pdf.addPage() }
>         ).from(pages[j]).toContainer().toCanvas().toPdf()
>       }
>       doc.save()  
> ```

I used this approach it works but the problem is when I enable the links all the links are into a single page 
any solution for that case

**Comment by Puspa-Subedi** [comment] 2022-08-24 07:51
Hi @eKoopmans 

Can we merge the pdf created from elements with pdf?

Thanks in Advance

**Comment by 313ramsingh** [comment] 2023-03-16 10:23
Hi @eKoopmans

let doc = html2pdf().set(opt).from(pages[0]).toPdf()
      for (let j = 1; j < this.pages.length; j++) {
        doc = doc.get('pdf').then(
          pdf => { pdf.addPage() }
        ).from(pages[j]).toContainer().toCanvas().toPdf()
      }
      doc.save() 
I want to open this pdf in new window not wanted to save , how to do that doc.output() function not working getting error
Thanks in Advance
